### PR TITLE
Add a healthcheck instruction.

### PR DESCRIPTION
**Pull request by varshavaradarajan**
Will show up something like this -

screen shot 2017-10-09 at 10 20 37 am

@ketan - let me know if the defaults for the healthcheck is not good enough - https://docs.docker.com/engine/reference/builder/#healthcheck

I will add the healthcheck instruction to the server once https://github.com/gocd/gocd/pull/3912 is merged

### CODE REVIEW

**Comment by ketan** [comment]
I am not sure that we should have a health check by default. Makes it hard for anyone to know why the container suddenly exits when they are debugging things. Additionally older versions of docker do not support health checks.

Probably adding a note to readme that a health check is possible, and users should add it to the image they inherit from our images makes more sense?

**Comment by varshavaradarajan** [comment]
> Makes it hard for anyone to know why the container suddenly exits when they are debugging things.

Can you elaborate on this? I thought if there was a problem with the container starting up, docker logs will help. The custom healthcheck is for when the container is running but the agent hasn't connected to the server. Docker will report that container is unhealthy. It won't terminate it. 

As for the older versions, `healthcheck` was introduced in [1.12](https://docs.docker.com/release-notes/docker-engine/#1120-2016-07-28) which was August 2016, do you not think we should add this after more than a year's interval..?

**Comment by ketan** [comment]
1.12 seems reasonable. Do you think any of the params need to be
parametrization? Env vars or such?

**Comment by arvindsv** [comment]
I suppose an env var to turn it off? In a swarm-like setup, it's possible that the agent will be killed if unhealthy. We could argue it is desirable to do so, though.

**Comment by ketan** [comment]
> I suppose an env var to turn it off? In a swarm-like setup, it's possible that the agent will be killed if unhealthy. We could argue it is desirable to do so, though.

It is very much desirable in a swarm like setup. However in a couple of instances, when the server is swamped because of the thundering-herd problem you talk about. The 1 minute delay will actually make the problem more severe.

**Pull request closed without merging**
